### ISSUE TITLE
SLIP.git

### ISSUE THREAD

**Issue by VictorBoutin** [laurentperrinet/SHL_scripts#2]
pip3 install -U git+https://github.com/laurentperrinet/SLIP.git 
is still bugging when trying to install

**Comment by laurentperrinet** [comment]
thanks! These repositories moved to https://github.com/bicv/SLIP

similarly, this repo moved to https://github.com/bicv/SHL_scripts

**Comment by laurentperrinet** [comment]
solved in https://github.com/laurentperrinet/SHL_scripts/commit/cbe74f5c351c84b6863a559fc0c2a04b993f34ed
